### ISSUE TITLE
Crashing Issue 

### ISSUE THREAD

**Issue by FlagWhat** [lmarianski/Device-Mod-Apps#15]
There is a Problem when installing this mod. this mod crashes your game and we do not know why. it may only work on others except us and we do not know why this keeps crashing people may hate MrcrayFish Now it's 2018 and it may be an issue but sadly i,ll never let us Go Back in 1.12.2 please tell us why this keeps crashing.

![is](https://user-images.githubusercontent.com/45490763/49295444-bde48a80-f4f0-11e8-95dd-59bd39206999.png)

**Comment by lukas2005** [comment]
The mod is broken

**Comment by JohnLennonPlayz** [comment]
when i open the world it says A fatal error has occurred, this connection is terminated. plz fix it

**Comment by funfunfunny** [comment]
Can you fix the mod please I am soooo San it’s broken
