### ISSUE TITLE
Read this

### ISSUE THREAD

**Issue by JohnLennonPlayz** [lmarianski/Device-Mod-Apps#16]
hey please use mcef

**Comment by funfunfunny** [comment]
How

**Comment by JohnLennonPlayz** [comment]
please Use Minecraft Chormium Embended Framework

**Comment by JohnLennonPlayz** [comment]
and renew your mod beacause your mod is broken

**Comment by grillo78** [comment]
https://minecraft.curseforge.com/projects/apps-mod I use mcef for asimilar mod

**Comment by JohnLennonPlayz** [comment]
im using your mod grillo78

**Comment by JohnLennonPlayz** [comment]
i want to use this mod

**Comment by lmarianski** [comment]
You know that the mod this is an addon for is discontinued...
