### ISSUE TITLE
This mod crashes on forge 1.12.2

### ISSUE THREAD

**Issue by SirLotsaLocks** [lmarianski/Device-Mod-Apps#17]
This mod is crashing on forge 1.12.2
I think I figured out why. It creates a file in the folder /mods/1.12.2/ called lda-0.1.6.corePlugin and as long as that file is there I can't join any worlds even after removing the actual mod because lda-0.1.6.corePlugin is still there. I don't know how easy that would be to fix but I just wanted to put this out there for others who are experiencing "a fatal error has occurred this connection is terminated"

**Comment by lmarianski** [comment]
That's the coremod required for some features to work. I'm not really updating this thing anymore tho
